[package]
name = "huncomma_terminal"
version = "0.1.0"
authors = ["Tasnádi Zoltán <tasnadi98@freemail.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
huncomma = "0.2.1"
logos = "0.11.4"
clap = "2.33.1"
